name: Run Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4"
    
    - name: Set up LuaRocks
      uses: leafo/gh-actions-luarocks@v4
    
    - name: Install dependencies
      run: |
        luarocks install busted
        luarocks install luacov
        luarocks install luacheck
    
    - name: Create .lua structure
      run: |
        mkdir -p .lua/share/lua/5.4
        mkdir -p .lua/lib/lua/5.4
        mkdir -p .lua/bin
    
    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE
        busted --pattern=".lua" tests/unit/
      env:
        CI: true
    
    - name: Run linter
      run: |
        # Allow the known string metatable warning
        result=$(luacheck . --quiet --formatter plain)
        warning_count=$(echo "$result" | grep -c "warning")
        error_count=$(echo "$result" | grep -c "error")
        
        echo "Warnings: $warning_count, Errors: $error_count"
        
        if [ "$error_count" -gt 0 ]; then
          echo "Found errors in linting:"
          echo "$result"
          exit 1
        fi
        
        if [ "$warning_count" -gt 1 ]; then
          echo "Found too many warnings in linting:"
          echo "$result"
          exit 1
        fi
        
        echo "Linting passed (with acceptable warnings)"
    
    - name: Upload coverage reports (if configured)
      if: success()
      run: |
        if command -v codecov >/dev/null 2>&1; then
          codecov
        else
          echo "Codecov tool not installed, skipping upload"
        fi
