name: Run Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup environment
      run: |
        # Install Lua and dependencies via apt
        sudo apt-get update
        sudo apt-get install -y lua5.4 lua5.4-dev luarocks
        
        # Print diagnostics
        lua -v || lua5.4 -v
        luarocks --version
        
    - name: Install test dependencies
      run: |
        # Install test dependencies
        sudo luarocks install busted
        sudo luarocks install luacov
        sudo luarocks install luacheck
        
    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE
        busted --verbose tests/unit/
