name: Run Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4"
    
    - name: Set up LuaRocks
      uses: leafo/gh-actions-luarocks@v4
    
    - name: Install dependencies
      run: |
        luarocks install busted
        luarocks install luacov
        luarocks install luacheck
    
    - name: Debug environment
      run: |
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        ls -la $GITHUB_WORKSPACE
        ls -la $GITHUB_WORKSPACE/tests
    
    - name: Create .lua structure
      run: |
        mkdir -p .lua/share/lua/5.4
        mkdir -p .lua/lib/lua/5.4
        mkdir -p .lua/bin
    
    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE
        busted --pattern=".lua" tests/unit/
      env:
        CI: true
    
    - name: Run linter
      run: |
        # Tolerate a small number of warnings (up to 5) but fail on errors
        luacheck . || [ $? -eq 1 ] && [ "$(luacheck . 2>&1 | grep -c "warning")" -le 5 ]
    
    - name: Upload coverage reports (if configured)
      if: success()
      run: |
        if command -v codecov >/dev/null 2>&1; then
          codecov
        else
          echo "Codecov tool not installed, skipping upload"
        fi
