name: Run Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Windows compatibility setup if needed
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
      
    # Setup Lua using a well-maintained fork of leafo's action
    - name: Setup Lua
      uses: xpol/setup-lua@v1
      with:
        lua-version: "5.4"
        
    # Setup LuaRocks using xpol's action (which is compatible with setup-lua)
    - name: Setup LuaRocks
      uses: xpol/setup-luarocks@v1
      
    # Print debugging information
    - name: Environment Info
      run: |
        lua -v
        luarocks --version
        echo "PATH: $PATH"
        echo "LUA_PATH: $LUA_PATH"
        
    # Install dependencies
    - name: Install dependencies
      run: |
        luarocks install busted
        luarocks install luacheck
        
    # Run tests
    - name: Run tests
      run: |
        busted --verbose tests/unit/
        
    # Run linter with tolerance for warnings
    - name: Run linter
      run: |
        luacheck . || [ $? -eq 1 ] && echo "Linting warnings are acceptable"
