name: Run Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Lua
      uses: leafo/gh-actions-lua@v8.1.0
      with:
        luaVersion: "5.4"
    
    - name: Set up LuaRocks
      uses: leafo/gh-actions-luarocks@v4
    
    - name: Debug environment
      run: |
        echo "Lua version:"
        lua -v
        echo "LuaRocks version:"
        luarocks --version
        echo "Current directory:"
        pwd
        echo "Directory listing:"
        ls -la
        echo "PATH:"
        echo $PATH
        echo "Which lua:"
        which lua || echo "lua not found in PATH"
    
    - name: Install dependencies
      run: |
        luarocks install busted
        luarocks install luacheck
    
    - name: Run tests
      run: |
        ~/.lua/bin/busted --verbose tests/unit/
    
    - name: Run linter
      run: |
        # Allow the known string metatable warning
        ~/.lua/bin/luacheck . --exclude-files ".lua/**/*.lua" || [ $? -eq 1 ] && echo "Linting warnings are acceptable"
